### ISSUE TITLE
No Data reciver  Apache kafka apache spark

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [dibbhatt/kafka-spark-consumer#13]
hi i'am using apache kafka and apache spark 1.3 and i test this code 
def main(args: Array[String]) {
    val ctx = new SparkContext("local[4]", "Spark Streamin")
     val kafkaParams = Map("metadata.broker.list" -> "127.0.1:2182")
    val topics = Set("page_visits")
    val kafkaStream = KafkaUtils.createDirectStream[String, String, StringDecoder, StringDecoder](ssc,  kafkaParams, topics)
    kafkaStream.foreachRDD(rdd => print())
    ssc.start()
    ssc.awaitTermination()
  }
and my tomic its work when i start java programme too produce and consume data but in streaming no reciver data 
Help pleas!

**Comment by dibbhatt** [comment]
I could not understand the exact problem . If you are facing issue with KafkaUtils.createDirectStream please ask the question in Spark user group .

This low level consumer is an alternative Receiver based consumer and have no relation to the API which you are using.

**Comment by sidahmedbenkhaoua** [comment]
ok thanks for your replay

**Comment by sidahmedbenkhaoua** [comment]
please telle me where i find kafka.consumer.id ?
