### ISSUE TITLE
Running application on 3 node cluster, 3 instances of the same application are shown with different user

### ISSUE THREAD

**Issue by sorabh89** [dibbhatt/kafka-spark-consumer#22]
I'm running this application on a 3 node cluster, 1 with root and other 2 with ec2-user. when I submit the application, it shows 3 instances in web UI, with the following users: 1 root and 2 ec2-user. 
But the 2 instances with ec2-user are in waiting state.

I'm submitting the application from root machine.

Not able to figure out the reason for this.

One more issue that I'm facing is :
Since the default Job scheduling in standalone mode in FIFO. I've reduced the cores for each application. So this works fine but if I try to run more than that i.e let say 5 application others go in waiting state.

Is there any other type of Job Scheduling that I can use for this, So that all the application can run in parallel with no one in waiting state.

**Comment by dibbhatt** [comment]
You can use spark.streaming.concurrentJobs  set to value greater than 1 which will execute more jobs in parallel. 

Taken from TD's response here : http://stackoverflow.com/questions/23528006/how-jobs-are-assigned-to-executors-in-spark-streaming


"Actually, in the current implementation of Spark Streaming and under default configuration, only job is active (i.e. under execution) at any point of time. So if one batch's processing takes longer than 10 seconds, then then next batch's jobs will stay queued.
This can be changed with an experimental Spark property "spark.streaming.concurrentJobs" which is by default set to 1. Its not currently documented (maybe I should add it).
The reason it is set to 1 is that concurrent jobs can potentially lead to weird sharing of resources and which can make it hard to debug the whether there is sufficient resources in the system to process the ingested data fast enough. With only 1 job running at a time, it is easy to see that if batch processing time < batch interval, then the system will be stable. Granted that this may not be the most efficient use of resources under certain conditions. We definitely hope to improve this in the future."

**Comment by sorabh89** [comment]
Thanks Dibbhatt,

I got this working by setting the number of cores at the application level. Its not a good approach but yet worked for me.

I am facing 1 more issue. In my spark setup I've created 10 executors on 3 worker nodes, 6 on 1 and 2-2 on other 2.
But only half of the executors are processing the jobs i.e. 5, remaining are just not doing anything. I noticed this using the Spark webui.
And these are exactly half for each node i.e. 3,1,1 for 3 nodes. Don't know the reason for this.
This seems to be because of my cluster settings.
Just 1 more thing I'm a little confused about the actual difference between worker instances and executor instances. Should we equal no. of worker and executor, and also the number of cores needed by them?

**Comment by sorabh89** [comment]
Sometimes the executors processing the tasks are even less than half.

**Comment by dibbhatt** [comment]
This should clear your concept on Worker , Executor , Cores and Executor-Core..

http://blog.cloudera.com/blog/2015/03/how-to-tune-your-apache-spark-jobs-part-2/

Are you running on YARN mode or Standalone mode ? 

Just to mention , prior to Spark 1.4 , In Standalone mode you can only have 1 executor per worker .

**Comment by sorabh89** [comment]
I am running on standalone mode and using spark 1.4
