### ISSUE TITLE
After some hours not processing because of executor fail error

### ISSUE THREAD

**Issue by sorabh89** [dibbhatt/kafka-spark-consumer#23]
Hi Dibbhatt,

I am facing some issue, when using this project for a longer duration.

ERROR TaskSchedulerImpl: Lost executor 0 on <someIp>: Executor heartbeat timed out after 161334 ms
[Stage 2:>                  (0 + 4) / 4][Stage 1019:>               (0 + 0) / 2]15/08/14 20:58:10 ERROR TaskSchedulerImpl: Lost executor 1 on <someIp>: remote Rpc client disassociated
15/08/14 20:58:10 ERROR SparkDeploySchedulerBackend: Asked to remove non-existent executor 1
[Stage 2:>                  (0 + 4) / 4][Stage 1019:>               (0 + 0) / 2]15/08/14 20:59:47 ERROR TaskSchedulerImpl: Lost an executor 1 (already removed): Executor heartbeat timed out after 124846 ms
[Stage 2:>                  (0 + 4) / 4][Stage 1019:>               (0 + 0) / 2]15/08/14 21:08:47 ERROR TaskSchedulerImpl: Lost executor 0 on <someIp>: Executor heartbeat timed out after 146607 ms
[Stage 2:>                  (0 + 4) / 4][Stage 1019:>               (0 + 0) / 2]15/08/14 21:24:20 ERROR TaskSchedulerImpl: Lost executor 5 on <someIp>: remote Rpc client disassociated
15/08/14 21:24:20 ERROR SparkDeploySchedulerBackend: Asked to remove non-existent executor 5
[Stage 2:>                  (0 + 4) / 4][Stage 1019:>               (0 + 0) / 2]15/08/14 21:26:47 ERROR TaskSchedulerImpl: Lost an executor 5 (already removed): Executor heartbeat timed out after 165821 ms

I am using a 2 node cluster with 4 executors on each and with 5 GB and 2 cores for each executor.

One more question that I have is :

This consumer always gives data from the last saved offset, Is there a way to neglect that offset and receive only the real time data?

Regards,
Sorabh

**Comment by dibbhatt** [comment]
Not sure about Executor loss issue ? Can you see something in executor log ?

Regarding starting from last saved offset, the consumer will always start from last saved offset. If you want the consumer to start form most latest offset , you can probably delete the ZK Path where you store the offset location (zookeeper.consumer.path) and set consumer.forcefromstart to false when you restart the consumer. Then it will start from latest offset every time you restart the consumer.

**Comment by sorabh89** [comment]
Hi Dibbhatt,

Thanks for your quick reply.

I am having 1 more issue, it is not related to this topic but since you have good knowledge of Spark so I thought you can help..... :)

I want to connect to more than 1 cassandra host, using cassandra connector we can give 1 host in SparkConf. But I need to connect to another host as well. Is there a way to do it?

Your expertise will be of great help..

Regards,
Sorabh

**Comment by sorabh89** [comment]
There is 1 more issue, some of the tasks are shown as skipped in the UI, however I am able to process the data.
As per your earlier clarification, the processing time should be less than the streaming duration.
As per the SOPs I used in my program the processing time is definitely less than streaming duration then why am I getting these messages regarding task skipping (48/48 (96 skipped)).

And in the UI it shows 3-4 foreachRDD call in 1 batch interval, what is the reason behind this? since I have called it only once.

Regards, 
Sorabh

**Comment by dibbhatt** [comment]
I am sorry, I can not help you on Cassandra connector part as I have less experience using Cassandra with Spark. Regarding wrong UI stats , are you using Speculative Execution by any chance ?

**Comment by sorabh89** [comment]
No, I am not using any Speculative Execution.

**Comment by dibbhatt** [comment]
Hi,

**Comment by dibbhatt** [comment]
Released version 1.0.4 of Kafka Spark Consumer in spark-packages. 

http://spark-packages.org/package/dibbhatt/kafka-spark-consumer

This consumer now can control the Spark Memory Back Pressure problem by having a inbuilt PID ( Proportional , Integral , Derivative ) Controller to rate limit the block size at run time. Please refer to Readme how this is different from existing Out-of-the-Box Spark Kafka Consumer, and how this is different from upcoming Spark 1.5 Back-Pressure implementation.
