### ISSUE TITLE
How to decode byte messages from Kafka

### ISSUE THREAD

**Issue by fzschornack** [dibbhatt/kafka-spark-consumer#24]

**Comment by dibbhatt** [comment]
Hi, 

Did you figure it out how to get the byte messages from Kafka ? 

The ReceiverLauncher.launch returns the DStream<MessageAndMetadata> or JavaDStream<MessageAndMetadata> (for Java) , and you can call the getPayload on MessageAndMetadata object to get the byte array...

Something like this ..


val tmp_stream = ReceiverLauncher.launch(ssc, props, numberOfReceivers,StorageLevel.MEMORY_ONLY)

//Lets convert the Array[Byte] to String
val stream = tmp_stream.map(x => { val s = new String(x.getPayload); s })

**Comment by fzschornack** [comment]
Hi,

Yes, I figured out few hours ago. I tried to delete the issue but I
couldn't, sorry to bother you.

I did exactly as you said and used the payload. It is working fine.

Thank you so much for creating this receiver, it helped me a lot!

Best,

**Comment by dibbhatt** [comment]
Hi, 

Not an issue. You can raise any issue/question . Its perfectly fine. 

Glad to know this receiver is useful to you ..

**Comment by dibbhatt** [comment]
hi @fzschornack 


I have created a JIRA to track the progress of contributing back this project to Apache Spark.

https://issues.apache.org/jira/browse/SPARK-11045

This project is now presently in spark-packages and I believe this is the correct time to contribute it to Apache Spark Project and give better options to larger community around Kafka Connectivity for Spark Streaming.

kindly Vote for this JIRA.

**Comment by jedisct1** [comment]
Voted!

**Comment by dibbhatt** [comment]
thanks
