### ISSUE TITLE
Contributing Receiver based Low Level Kafka Consumer from Spark-Packages to Apache Spark Project

### ISSUE THREAD

**Issue by dibbhatt** [dibbhatt/kafka-spark-consumer#27]
Dear all , 

I have created a JIRA to track the progress of contributing back this project to Apache Spark.

https://issues.apache.org/jira/browse/SPARK-11045

This project is now presently in spark-packages and I believe this is the correct time to contribute it to Apache Spark Project and give better options to larger community around Kafka Connectivity for Spark Streaming. 

Those who are using this packages , kindly Vote for this JIRA.

**Comment by samklr** [comment]
+1

**Comment by dibbhatt** [comment]
Hi @samklr can you please vote against the JIRA please
