### ISSUE TITLE
Doesn't seems to be working

### ISSUE THREAD

**Issue by akhld** [dibbhatt/kafka-spark-consumer#3]
I gave this project a try, i cloned the repo, build the project and used that jar inside my SparkStreaming project and used your KafkaReceiver to create dstream. Whenever i run it, it just crashes with my SparkContext being shutdown.

You can look at the code over here https://gist.github.com/akhld/a59a2369f0f1f5509af4

This is what happens when i run it in Standalone mode https://gist.github.com/akhld/b5627bf866721df7321b

This is what happens when i run it in local mode https://gist.github.com/akhld/36baccb2a866106315f6

**Comment by akhld** [comment]
When you say commit the offset in ZK, does it mean my consumer machines should have write access to the ZK running on another cluster?

**Comment by dibbhatt** [comment]
No you may not have. That is the reason I kept two properties for ZK settings. One for reading Kafka broker details and other for committing the read offset. You can have two separate cluster for that. We at pearaon have separate zk cluster for Kafka and storing comitted offset.

Dibyendu

Sent from Samsung Mobile

Akhil Das <notifications@github.com> wrote:

When you say commit the offset in ZK, does it mean my consumer machines should have write access to the ZK running on another cluster?

**Comment by akhld** [comment]
Awesome.!

**Comment by akhld** [comment]
Hi Dibyendu,
One more thing i want to clarify, so my batch duration is 2 seconds and i'm consuming around 600MB of data at once, and it takes ~8 seconds to process the whole data. Mean while my kafka producer keeps on pushing data to the topic and after 8 seconds the consumer is consuming about 2-3GB of data which lags drastically/throws up exceptions. Any workaround on these? I tried limiting the parameters in KafkaConfig.java but couldn't get a proper number.

**Comment by dibbhatt** [comment]
Hi Akhil, 
Here are two tuning options you need to try..
You can see following two variables KafkaConfig.javaAs the SimpleConsumer is generating the Block itself and push the block to BlockManager, the BlockInterval is controlled by the consumer itself ( The Spark specific property spark.streaming.blockInterval does not have any affect ).This is the default value..public int _fetchSizeBytes = 512 * 1024;
public int _fillFreqMs = 200 ;
This suggests that, Receiver for any given Partition of a Topic will pull 512 KB Block of data at every 200ms. With this default settings, let assume your Kafka Topic have 5 partitions, and your Spark Batch Duration is say 10 Seconds, this Consumer will pull512 KB x ( 10 seconds / 200 ms ) x 5 = 128 MB of data for every Batch.If you need higher rate, you can increase the _fetchSizeBytes , or if you need less number of Block generated you can increase _fillFreqMs.These two parameter need to be carefully tuned keeping in mind your downstream processing rate and your memory settings.I guess you are tuning the _fetchSizeBytes value. You can try increasing the _fillFreqMs and see if that will affect ( This will lower the number of blocks generated in a given Batch Interval ).Dibyendu 

     On Saturday, 28 February 2015 12:24 PM, Akhil Das <notifications@github.com> wrote:
   

 Hi Dibyendu,
One more thing i want to clarify, so my batch duration is 2 seconds and i'm consuming around 600MB of data at once, and it takes ~8 seconds to process the whole data. Mean while my kafka producer keeps on pushing data to the topic and after 8 seconds the consumer is consuming about 2-3GB of data which lags drastically/throws up exceptions. Any workaround on these? I tried limiting the parameters in KafkaConfig.java but couldn't get a proper number.—

**Comment by akhld** [comment]
Thanks for the detailed response Dibyendu.
