### ISSUE TITLE
How to use the application to handle multi topic

### ISSUE THREAD

**Issue by zdxMike** [dibbhatt/kafka-spark-consumer#40]

**Comment by dibbhatt** [comment]
Yes, it a open issue still. This consumer can not handle multi topic. But if this a urgent need from community , I can bring this in.

**Comment by zdxMike** [comment]
Thank you for your answer.

I am looking forward to you can bring this in.

**Comment by yycnik** [comment]
Is there a workaround for this issue? I tried creating separate streams and then use union to merge them but did not work. Also could you, please, outline the scope of the work needed to support multi topic?

**Comment by ritesh-dineout** [comment]
Yes this is a major drawback for this consumer. Spark out-of-box kafka streaming supports this.

Kindly add this at the earliest.

**Comment by dibbhatt** [comment]
Hi, I can understand this. I will work on it to add multi topic support. Will keep you posted.

**Comment by yangcong3643** [comment]
Does it come true now?

**Comment by jfgosselin** [comment]
I also need multi topic support.

**Comment by dibbhatt** [comment]
Hi All. Just released Version 2.1.0 that supports Kafka Multi Topic fetch. Example is mentioned in Readme file. Kindly let me know how this goes . 

Sorry I keep you all waiting for such a long time for this, this was over due for quite sometime .

**Comment by dibbhatt** [comment]
Sample code you can see here :

https://github.com/dibbhatt/kafka-spark-consumer#handling-multi-topic

**Comment by dibbhatt** [comment]
Hi, let me know if anyone tried multi topic feature . Then I can close this ticket

**Comment by dibbhatt** [comment]
closing this ticket.
