### ISSUE TITLE
ReceiverLauncher.launch can not get data

### ISSUE THREAD

**Issue by zlkkuu** [dibbhatt/kafka-spark-consumer#43]
The blow is the log of the application, in the log i found spark dstream always consume the kafka, but it can not do nothing.

My code:
val tmp_stream = ReceiverLauncher.launch(ssc, props, numberOfReceivers, StorageLevel.MEMORY_ONLY)
        tmp_stream.foreachRDD(rdd => {
            if (!rdd.isEmpty()){
                val today = DateTime.now
                val nowDay = today.toString("yyyy-MM-dd")
                val lastDay = today.minusDays(1).toString("yyyy-MM-dd")
                val nowDayType = today.toString("yyyy.MM.dd")
                val lastDayType = today.minusDays(1).toString("yyyy.MM.dd")
                println(nowDay)
                sqlContext.createDataFrame(rdd.map(x => new String(x.getPayload, "UTF-8"))
                          .flatMap(checkClick), affiliate_data_schema).where(s"dt = '${nowDay}'")
                          .saveToEs(s"spark-aflt-all-record-${nowDayType}/record", esconf)
                sqlContext.createDataFrame(rdd.map(x => new String(x.getPayload, "UTF-8"))
                          .flatMap(checkClick), affiliate_data_schema).where(s"dt = '${lastDay}'")
                          .saveToEs(s"spark-aflt-all-record-${lastDayType}/record", esconf)
            } else {
                println("rdd is empty")
            }
        } )

- 17/02/28 21:37:06 INFO Version: Elasticsearch Hadoop v5.0.0-alpha5 [c513369b06]
- 17/02/28 21:37:07 INFO EsDataFrameWriter: Writing to [spark-aflt-all-record-2017.02.28/record]
- 17/02/28 21:37:07 INFO EsDataFrameWriter: Writing to [spark-aflt-all-record-2017.02.28/record]

17/02/28 21:37:02 INFO MemoryStore: Block broadcast_6 stored as values in memory (estimated size 40.3 KB, free 1618.0 MB)
17/02/28 21:37:02 INFO PartitionManager: Consumed offset 2438034718 for Partition 1 written to ZK
17/02/28 21:37:03 INFO MemoryStore: Block input-1-1488346622800 stored as values in memory (estimated size 1055.5 KB, free 1617.0 MB)
17/02/28 21:37:03 INFO BlockGenerator: Pushed block input-1-1488346622800
17/02/28 21:37:03 INFO BlockManager: Found block input-1-1488346618800 locally
17/02/28 21:37:03 INFO BlockManager: Found block input-1-1488346619000 locally
17/02/28 21:37:03 INFO PartitionManager: Consumed offset 2438036464 for Partition 1 written to ZK
17/02/28 21:37:04 INFO MemoryStore: Block input-1-1488346623800 stored as values in memory (estimated size 1035.7 KB, free 1616.0 MB)
17/02/28 21:37:04 INFO BlockGenerator: Pushed block input-1-1488346623800
17/02/28 21:37:04 INFO PartitionManager: Consumed offset 2438036893 for Partition 1 written to ZK
17/02/28 21:37:05 INFO MemoryStore: Block input-1-1488346624800 stored as values in memory (estimated size 248.7 KB, free 1615.7 MB)
17/02/28 21:37:05 INFO BlockGenerator: Pushed block input-1-1488346624800
17/02/28 21:37:05 INFO CodeGenerator: Code generated in 1382.889398 ms
17/02/28 21:37:05 INFO CodeGenerator: Code generated in 289.775591 ms
17/02/28 21:37:05 INFO PartitionManager: Consumed offset 2438037051 for Partition 1 written to ZK
17/02/28 21:37:06 INFO MemoryStore: Block input-1-1488346625800 stored as values in memory (estimated size 99.6 KB, free 1615.6 MB)
17/02/28 21:37:06 INFO BlockGenerator: Pushed block input-1-1488346625800
17/02/28 21:37:06 INFO CodeGenerator: Code generated in 341.839913 ms
17/02/28 21:37:06 INFO Version: Elasticsearch Hadoop v5.0.0-alpha5 [c513369b06]
17/02/28 21:37:07 INFO EsDataFrameWriter: Writing to [spark-aflt-all-record-2017.02.28/record]
17/02/28 21:37:07 INFO EsDataFrameWriter: Writing to [spark-aflt-all-record-2017.02.28/record]or: Pushed block input-1-1488346628800
17/02/28 21:37:10 INFO PartitionManager: Consumed offset 2438037474 for Partition 1 written to ZK
17/02/28 21:37:11 INFO MemoryStore: Block input-1-1488346630800 stored as values in memory (estimated size 88.7 KB, free 1615.4 MB)
17/02/28 21:37:11 INFO BlockGenerator: Pushed block input-1-1488346630800
17/02/28 21:37:11 INFO PartitionManager: Consumed offset 2438037671 for Partition 1 written to ZK
17/02/28 21:37:12 INFO MemoryStore: Block input-1-1488346631800 stored as values in memory (estimated size 121.1 KB, free 1615.3 MB)
17/02/28 21:37:12 INFO BlockGenerator: Pushed block input-1-1488346631800
17/02/28 21:37:12 INFO PartitionManager: Consumed offset 2438037859 for Partition 1 written to ZK
17/02/28 21:37:13 INFO MemoryStore: Block input-1-1488346632800 stored as values in memory (estimated size 115.8 KB, free 1615.1 MB)
17/02/28 21:37:13 INFO BlockGenerator: Pushed block input-1-1488346632800
17/02/28 21:37:14 INFO CodeGenerator: Code generated in 909.674488 ms
17/02/28 21:37:15 INFO PartitionManager: Consumed offset 2438038010 for Partition 1 written to ZK
17/02/28 21:37:16 INFO MemoryStore: Block input-1-1488346635800 stored as values in memory (estimated size 95.0 KB, free 1615.0 MB)
17/02/28 21:37:16 INFO BlockGenerator: Pushed block input-1-1488346635800
17/02/28 21:37:16 INFO Executor: Finished task 3.0 in stage 6.0 (TID 79). 1366 bytes result sent to driver
17/02/28 21:37:16 INFO PartitionManager: Consumed offset 2438038227 for Partition 1 written to ZK
17/02/28 21:37:17 INFO MemoryStore: Block input-1-1488346636800 stored as values in memory (estimated size 136.0 KB, free 1614.9 MB)
17/02/28 21:37:17 INFO BlockGenerator: Pushed block input-1-1488346636800
17/02/28 21:37:17 INFO Executor: Finished task 2.0 in stage 6.0 (TID 77). 2165 bytes result sent to driver
17/02/28 21:37:18 INFO PartitionManager: Consumed offset 2438038614 for Partition 1 written to ZK
17/02/28 21:37:19 INFO MemoryStore: Block input-1-1488346638800 stored as values in memory (estimated size 240.8 KB, free 1614.7 MB)
17/02/28 21:37:19 INFO BlockGenerator: Pushed block input-1-1488346638800
17/02/28 21:37:21 INFO PartitionManager: Consumed offset 2438038949 for Partition 1 written to ZK
17/02/28 21:37:21 INFO MemoryStore: Block input-1-1488346641000 stored as values in memory (estimated size 209.7 KB, free 1614.5 MB)
17/02/28 21:37:21 INFO BlockGenerator: Pushed block input-1-1488346641000
17/02/28 21:37:22 INFO PartitionManager: Consumed offset 2438039279 for Partition 1 written to ZK
17/02/28 21:37:22 INFO MemoryStore: Block input-1-1488346642000 stored as values in memory (estimated size 207.3 KB, free 1614.3 MB)
17/02/28 21:37:22 INFO BlockGenerator: Pushed block input-1-1488346642000
17/02/28 21:37:24 INFO PartitionManager: Consumed offset 2438039451 for Partition 1 written to ZK
17/02/28 21:37:24 INFO MemoryStore: Block input-1-1488346644000 stored as values in memory (estimated size 106.9 KB, free 1614.2 MB)
17/02/28 21:37:24 INFO BlockGenerator: Pushed block input-1-1488346644000
17/02/28 21:37:26 INFO PartitionManager: Consumed offset 2438039633 for Partition 1 written to ZK
17/02/28 21:37:26 INFO MemoryStore: Block input-1-1488346646000 stored as values in memory (estimated size 113.0 KB, free 1614.1 MB)
17/02/28 21:37:26 INFO BlockGenerator: Pushed block input-1-1488346646000
17/02/28 21:37:27 INFO PartitionManager: Consumed offset 2438039793 for Partition 1 written to ZK
17/02/28 21:37:27 INFO MemoryStore: Block input-1-1488346647000 stored as values in memory (estimated size 98.4 KB, free 1614.0 MB)
17/02/28 21:37:27 INFO BlockGenerator: Pushed block input-1-1488346647000
17/02/28 21:37:31 INFO PartitionManager: Consumed offset 2438040131 for Partition 1 written to ZK
17/02/28 21:37:31 INFO MemoryStore: Block input-1-1488346651000 stored as values in memory (estimated size 210.8 KB, free 1613.8 MB)
17/02/28 21:37:31 INFO BlockGenerator: Pushed block input-1-1488346651000
17/02/28 21:37:36 INFO PartitionManager: Consumed offset 2438040293 for Partition 1 written to ZK
17/02/28 21:37:36 INFO MemoryStore: Block input-1-1488346656000 stored as values in memory (estimated size 101.0 KB, free 1613.7 MB)
17/02/28 21:37:36 INFO BlockGenerator: Pushed block input-1-1488346656000
17/02/28 21:37:39 INFO PartitionManager: Consumed offset 2438040484 for Partition 1 written to ZK
17/02/28 21:37:39 INFO MemoryStore: Block input-1-1488346659000 stored as values in memory (estimated size 121.8 KB, free 1613.5 MB)
17/02/28 21:37:39 INFO BlockGenerator: Pushed block input-1-1488346659000
17/02/28 21:37:41 INFO PartitionManager: Consumed offset 2438040614 for Partition 1 written to ZK
17/02/28 21:37:41 INFO MemoryStore: Block input-1-1488346661000 stored as values in memory (estimated size 81.1 KB, free 1613.5 MB)
17/02/28 21:37:41 INFO BlockGenerator: Pushed block input-1-1488346661000
17/02/28 21:37:42 INFO PartitionManager: Consumed offset 2438040749 for Partition 1 written to ZK
17/02/28 21:37:42 INFO MemoryStore: Block input-1-1488346662000 stored as values in memory (estimated size 83.3 KB, free 1613.4 MB)
17/02/28 21:37:42 INFO BlockGenerator: Pushed block input-1-1488346662000
17/02/28 21:37:43 INFO PartitionManager: Consumed offset 2438041118 for Partition 1 written to ZK
17/02/28 21:37:43 INFO MemoryStore: Block input-1-1488346663000 stored as values in memory (estimated size 228.7 KB, free 1613.2 MB)
17/02/28 21:37:43 INFO BlockGenerator: Pushed block input-1-1488346663000
17/02/28 21:37:47 INFO PartitionManager: Consumed offset 2438041299 for Partition 1 written to ZK
17/02/28 21:37:47 INFO MemoryStore: Block input-1-1488346667000 stored as values in memory (estimated size 114.0 KB, free 1613.0 MB)
17/02/28 21:37:47 INFO BlockGenerator: Pushed block input-1-1488346667000
17/02/28 21:37:49 INFO PartitionManager: Consumed offset 2438041670 for Partition 1 written to ZK
17/02/28 21:37:49 INFO MemoryStore: Block input-1-1488346669000 stored as values in memory (estimated size 231.0 KB, free 1612.8 MB)
17/02/28 21:37:49 INFO BlockGenerator: Pushed block input-1-1488346669000
17/02/28 21:37:51 INFO PartitionManager: Consumed offset 2438041997 for Partition 1 written to ZK
17/02/28 21:37:51 INFO MemoryStore: Block input-1-1488346671000 stored as values in memory (estimated size 206.4 KB, free 1612.6 MB)
17/02/28 21:37:51 INFO BlockGenerator: Pushed block input-1-1488346671000
17/02/28 21:37:53 INFO PartitionManager: Consumed offset 2438042157 for Partition 1 written to ZK
17/02/28 21:37:53 INFO MemoryStore: Block input-1-1488346673000 stored as values in memory (estimated size 102.0 KB, free 1612.5 MB)
17/02/28 21:37:53 INFO BlockGenerator: Pushed block input-1-1488346673000
17/02/28 21:37:56 INFO PartitionManager: Consumed offset 2438042349 for Partition 1 written to ZK
17/02/28 21:37:56 INFO MemoryStore: Block input-1-1488346676000 stored as values in memory (estimated size 116.8 KB, free 1612.4 MB)
17/02/28 21:37:56 INFO BlockGenerator: Pushed block input-1-1488346676000
17/02/28 21:37:57 INFO PartitionManager: Consumed offset 2438042826 for Partition 1 written to ZK
17/02/28 21:37:57 INFO MemoryStore: Block input-1-1488346677000 stored as values in memory (estimated size 251.6 KB, free 1612.2 MB)
17/02/28 21:37:57 INFO BlockGenerator: Pushed block input-1-1488346677000
17/02/28 21:37:58 INFO PartitionManager: Consumed offset 2438043001 for Partition 1 written to ZK
17/02/28 21:37:58 INFO MemoryStore: Block input-1-1488346678000 stored as values in memory (estimated size 109.5 KB, free 1612.0 MB)
17/02/28 21:37:58 INFO BlockGenerator: Pushed block input-1-1488346678000
17/02/28 21:38:01 INFO PartitionManager: Consumed offset 2438043002 for Partition 1 written to ZK
17/02/28 21:38:01 INFO MemoryStore: Block input-1-1488346681000 stored as values in memory (estimated size 968.0 B, free 1612.0 MB)
17/02/28 21:38:01 INFO BlockGenerator: Pushed block input-1-1488346681000
17/02/28 21:38:02 INFO PartitionManager: Consumed offset 2438043003 for Partition 1 written to ZK
17/02/28 21:38:02 INFO MemoryStore: Block input-1-1488346682000 stored as values in memory (estimated size 1232.0 B, free 1612.0 MB)
17/02/28 21:38:02 INFO BlockGenerator: Pushed block input-1-1488346682000
17/02/28 21:38:03 INFO PartitionManager: Consumed offset 2438043004 for Partition 1 written to ZK
17/02/28 21:38:03 INFO MemoryStore: Block input-1-1488346683000 stored as values in memory (estimated size 888.0 B, free 1612.0 MB)
17/02/28 21:38:03 INFO BlockGenerator: Pushed block input-1-1488346683000
17/02/28 21:38:04 INFO PartitionManager: Consumed offset 2438043005 for Partition 1 written to ZK
17/02/28 21:38:04 INFO MemoryStore: Block input-1-1488346684000 stored as values in memory (estimated size 1072.0 B, free 1612.0 MB)
17/02/28 21:38:04 INFO BlockGenerator: Pushed block input-1-1488346684000
17/02/28 21:38:05 INFO PartitionManager: Consumed offset 2438043006 for Partition 1 written to ZK
17/02/28 21:38:05 INFO MemoryStore: Block input-1-1488346685000 stored as values in memory (estimated size 1232.0 B, free 1612.0 MB)
17/02/28 21:38:05 INFO BlockGenerator: Pushed block input-1-1488346685000
17/02/28 21:38:06 INFO PartitionManager: Consumed offset 2438043007 for Partition 1 written to ZK
17/02/28 21:38:06 INFO MemoryStore: Block input-1-1488346686000 stored as values in memory (estimated size 1016.0 B, free 1612.0 MB)
17/02/28 21:38:06 INFO BlockGenerator: Pushed block input-1-1488346686000
17/02/28 21:38:07 INFO PartitionManager: Consumed offset 2438043008 for Partition 1 written to ZK
17/02/28 21:38:07 INFO MemoryStore: Block input-1-1488346687000 stored as values in memory (estimated size 1032.0 B, free 1612.0 MB)
17/02/28 21:38:07 INFO BlockGenerator: Pushed block input-1-1488346687000
17/02/28 21:38:08 INFO PartitionManager: Consumed offset 2438043009 for Partition 1 written to ZK
17/02/28 21:38:08 INFO MemoryStore: Block input-1-1488346688000 stored as values in memory (estimated size 1016.0 B, free 1612.0 MB)
17/02/28 21:38:08 INFO BlockGenerator: Pushed block input-1-1488346688000
17/02/28 21:38:09 INFO PartitionManager: Consumed offset 2438043011 for Partition 1 written to ZK
17/02/28 21:38:09 INFO MemoryStore: Block input-1-1488346689000 stored as values in memory (estimated size 1384.0 B, free 1612.0 MB)
17/02/28 21:38:09 INFO BlockGenerator: Pushed block input-1-1488346689000
17/02/28 21:38:10 INFO PartitionManager: Consumed offset 2438043012 for Partition 1 written to ZK
17/02/28 21:38:10 INFO MemoryStore: Block input-1-1488346690000 stored as values in memory (estimated size 912.0 B, free 1612.0 MB)
17/02/28 21:38:10 INFO BlockGenerator: Pushed block input-1-1488346690000
17/02/28 21:38:11 INFO PartitionManager: Consumed offset 2438043013 for Partition 1 written to ZK

**Comment by dibbhatt** [comment]
I can see from the log that consumer is fetching messages from Kafka. What do you mean by "i found spark dstream always consume the kafka, but it can not do nothing." ?

What do you see in Spark UI ? Is your batches running fine or you see any error in the stages ? 

Dibyendu

**Comment by dibbhatt** [comment]
Do you still have this issue or you able to fix it ?

**Comment by dibbhatt** [comment]
hi @zlkkuu do you see this issue anymore ? If not shall I close this issue ?

**Comment by zlkkuu** [comment]
I am so sorry, it is my problem. Consumer kafka is ok. Thanks!

**Comment by dibbhatt** [comment]
awesome.. thanks a lot @zlkkuu
