### ISSUE TITLE
 java.lang.ClassNotFoundException: kafka.api.OffsetRequest

### ISSUE THREAD

**Issue by Hungsiro506** [dibbhatt/kafka-spark-consumer#44]
Hi, I got this problem when trying to run example. I'm using Spark 2.10, kafka 0.10_2.

**Comment by dibbhatt** [comment]
Can you share your Driver Code you wrote

**Comment by Hungsiro506** [comment]
Thanks for your support, it was my fault.  By the way, how can i fetch the messages by time duration instead of block size.
