### ISSUE TITLE
The log of application contain too many the messages of LOG.info

### ISSUE THREAD

**Issue by zlkkuu** [dibbhatt/kafka-spark-consumer#46]
Hi 
In the log of the application, I find too many messages of LOG.info, How can i avoid printing thess logs by other settings. Thanks!
For example:
![image](https://cloud.githubusercontent.com/assets/5002125/26707392/10e52ea2-4777-11e7-818a-f41067b44baf.png)

**Comment by dibbhatt** [comment]
Which version of consumer you are running. In latest I have fixed this issue. Otherwise , you can have your log4j properties where you mention the level as WARN for consumer.kafka package

**Comment by dibbhatt** [comment]
made default logging to WARN in latest 1.0.11 release.
