### ISSUE TITLE
How to use in kerberized context ?

### ISSUE THREAD

**Issue by StudioEtrange** [dibbhatt/kafka-spark-consumer#51]
In a context with Yarn and Kerberos where to pass this kind of options ?
`
kafkaParams.put("security.protocol", "SASL_SSL");
kafkaParams.put("ssl.truststore.location","./truststore");

kafkaParams.put("ssl.truststore.password", "pass");
`

**Comment by jiajf999** [comment]
同样的问题，关注

**Comment by dibbhatt** [comment]
Hi @StudioEtrange @jiajf999 I have made new release of the consumer 1.0.14 which now supports Kafka Security. Kindly let me know if you find any issue . ReadMe files has been updated with details ho to enable Kafka Security. 

https://github.com/dibbhatt/kafka-spark-consumer#kafka-security

**Comment by dibbhatt** [comment]
Hi,
You can see latest release. It supports the Kafka Security
    On Tuesday, 21 November, 2017, 10:51:54 PM GMT-5, jiajf999 <notifications@github.com> wrote:  
 
 
同样的问题，关注
