### ISSUE TITLE
Kafka Headers Support

### ISSUE THREAD

**Issue by agolomoodysaada** [dibbhatt/kafka-spark-consumer#55]
I'm aware that this consumer supports 0.11 brokers. Does it provide access to the kafka message [headers API](https://kafka.apache.org/documentation/#upgrade_1100_notable) that was added in 0.11 release?

**Comment by dibbhatt** [comment]
ConsumerRecord.headers() is not exposed yet. But this is easy to add . Let me know if I need to enable it

**Comment by agolomoodysaada** [comment]
Please enable it. That would be great since it enables the use of [OpenTracing](http://opentracing.io/) within Spark.
Thank you so much! If it's a lot of work, let me know how I can contribute it, I would just need some guidance.

**Comment by dibbhatt** [comment]
Hi @agolomoodysaada . I have made initial changes to support Kafka 0.11 header here

**Comment by dibbhatt** [comment]
https://github.com/dibbhatt/kafka-spark-consumer/commit/001b9f257430fe582b152eea8368a09017650edc

**Comment by dibbhatt** [comment]
Please take a look and try this out to see if this works for you. Then I will make a spark-packages release . Note this will only work with Kafka 0.11, so this will not be backward compatible with earlier Kafka version. You can do git clone, and build it locally, and write your Consumer client code . You can see the example consumer code in Readme , or in the above commit as well.

**Comment by dibbhatt** [comment]
hi @agolomoodysaada ,did you tried the Kafka Header support ? Please let me know, then I can close this issue.

**Comment by agolomoodysaada** [comment]
Hey @dibbhatt . Thank you so much for following up and making the update. We won't be able to test this for a while. But the code looks good so we can go ahead and close this.

Thank you
