### ISSUE TITLE
How to recover  the failed receiver  on a partition which has  exception of " Offsets out of range with no configured reset policy for partitions:"

### ISSUE THREAD

**Issue by yufuxin** [dibbhatt/kafka-spark-consumer#57]
Hello Dibyendu,
When a partition met a exception of "Offsets out of range with no configured reset policy for partitions: ", then this partition no longer works,   how to recover the receiver for the failed partition?
following is the details log message:

18/09/20 00:32:40 WARN PartitionManager: Got fetch request with offset out of range: 313303788 for Topic tr69data24  partition 19
18/09/20 00:32:40 WARN PartitionManager: Offset reset to LatestTime 313303788 for Topic tr69data24  partition 19
18/09/20 00:32:40 ERROR KafkaSparkConsumer: Partition 19 encountered error during createStream : Offsets out of range with no configured reset policy for partitions: {tr69data24-19=313303788}
consumer.kafka.OutOfRangeException: Offsets out of range with no configured reset policy for partitions: {tr69data24-19=313303788}
        at consumer.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:75)
        at consumer.kafka.PartitionManager.fetchMessages(PartitionManager.java:278)
        at consumer.kafka.PartitionManager.fill(PartitionManager.java:195)
        at consumer.kafka.PartitionManager.next(PartitionManager.java:134)
        at consumer.kafka.KafkaSparkConsumer.createStream(KafkaSparkConsumer.java:96)
        at consumer.kafka.KafkaSparkConsumer.run(KafkaSparkConsumer.java:118)
        at java.lang.Thread.run(Thread.java:745)
18/09/20 00:32:40 INFO ZooKeeper: Session: 0x265abf0f5a496a0 closed
18/09/20 00:32:40 INFO ClientCnxn: EventThread shut down
consumer.kafka.OutOfRangeException: Offsets out of range with no configured reset policy for partitions: {tr69data24-19=313303788}
        at consumer.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:75)
        at consumer.kafka.PartitionManager.fetchMessages(PartitionManager.java:278)
        at consumer.kafka.PartitionManager.fill(PartitionManager.java:195)
        at consumer.kafka.PartitionManager.next(PartitionManager.java:134)
        at consumer.kafka.KafkaSparkConsumer.createStream(KafkaSparkConsumer.java:96)
        at consumer.kafka.KafkaSparkConsumer.run(KafkaSparkConsumer.java:118)
        at java.lang.Thread.run(Thread.java:745)

18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 443585258 for Parittion 0
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 311429390 for Parittion 2
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 315225480 for Parittion 5
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 385262949 for Parittion 6
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 166297698 for Parittion 7
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 490824808 for Parittion 8
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 589901040 for Parittion 10
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 320172181 for Parittion 11
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 388380731 for Parittion 12
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 404124739 for Parittion 14
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 666967289 for Parittion 15
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 434333538 for Parittion 16
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 368144106 for Parittion 17
**18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 244265022 for Parittion 18
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 445694201 for Parittion 20**
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 205794190 for Parittion 21
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 420965741 for Parittion 22
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 338009268 for Parittion 23
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 389383488 for Parittion 24
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 444850876 for Parittion 26
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 254682257 for Parittion 28
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 296762823 for Parittion 29
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 280982673 for Parittion 30
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 148408705 for Parittion 31
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 345764987 for Parittion 32
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 198189174 for Parittion 34
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 153297639 for Parittion 35
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 345925489 for Parittion 36
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 353553758 for Parittion 37
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 293651243 for Parittion 38
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 457799405 for Parittion 40
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 352548943 for Parittion 42
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 373666232 for Parittion 43
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 450144063 for Parittion 44
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 200918074 for Parittion 45
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 55549751 for Parittion 46
18/09/20 09:41:00 INFO ProcessedOffsetManager: Wrote processed offset 266091161 for Parittion 47

Thanks,
Fred

**Comment by dibbhatt** [comment]
which version you are using ?

did restart of the streaming application won't solve the problem also ?

so this scenario can happen for case say Kafka Broker went down (which was Leader of partition 19 ) and the new elected Leader was behind the previous leader . e.g. let say broker X was leader for partition 19 was at offset 100 when failure happen, and when new Broker Y elected as leader, that have the latest offset say 50 for partition 19. Ideally the code should automatically reset back to 50 for broker Y. 

I will look into why this is not happening. But for a workaround, you can try this.

1. Stop the consumer
2. ./zkCli.sh -server xxxxx:2181 (Open the ZK CLI.  -server should be the server where offset commit is happening)

3. Go to this path /consumers/<your kafka.consumer.id>/offsets/<your topic>/19
You would see that offset value 313303788 there

4. remove this path from ZK..

rmr /consumers/<your kafka.consumer.id>/offsets/<your topic>/19

[if you do not want to loose data, you can go to kafka and find what is the earliest offset for partition 19. And can update (put) that value in this path as well]

5. Restart the consumer

Going forward, you can also make this changes in Kafka broker config unclean.leader.election.enable=false , this will make sure out of sync replica should not be selected as leader.

**Comment by yufuxin** [comment]
Hello Dibyendu,
I am using kafka-spark-consumer-1.0.14.jar.
When I restart  the streaming application, partition will continue works. 
Thanks, 
fred

**Comment by dibbhatt** [comment]
I see. Then the logic where it should Auto Reset back to latest offset for Leader of Partition (in case of broker failure) has some bug . I will look into this and will try to make a fix. Is this happening very frequent in your environment ?

**Comment by yufuxin** [comment]
Yes,  In my pre_production environment it happened several times in 24 hours,  It seems  in Spark this setting  kafkaParams.put("auto.offset.reset", "earliest")   doesn't  work. So each time the the "Out of offset" exception happened then will block the receiver.
Thanks,
Fred

**Comment by dibbhatt** [comment]
Ok.  This consumer should be smart enough to recover from any OffsetOutofRange issue, but I can see a bug in the logic. I can make a fix and commit the code. You can take it from github to make a build . If your test looks good, I can make a release. let me know if this sounds fine. Then I will try to make the fix soon.

**Comment by yufuxin** [comment]
ok, I will try it and response to you with the result.  Have you committed the code?

Thanks,
Fred Yu

**Comment by dibbhatt** [comment]
Not yet,will do in hour or two

**Comment by dibbhatt** [comment]
Hi, I have committed the code. You can pull the latest from git and build it locally. The version I changed to 1.0.15. Once you confirm things are fine, I will push this version to spark-packages

**Comment by yufuxin** [comment]
Hi, I can not pass the compile,  errors in ProcessedOffsetManager.java and  KafkaRangeReceiver.java.
Attached the sscreenshot.
Thanks
Fred 
![screenshot from 2018-09-20 19-52-34](https://user-images.githubusercontent.com/6129436/45852756-6ca96500-bd0f-11e8-9cd8-445c5b355c3a.png)

**Comment by yufuxin** [comment]
I am using java8 64bit JVM on Ubuntu 16.4 and the project compliance level 1.7.

**Comment by yufuxin** [comment]
Error message is :
The method mapPartitionsToPair(PairFlatMapFunction<Iterator<MessageAndMetadata<T>>,K2,V2>) in the type AbstractJavaDStreamLike<MessageAndMetadata<T>,JavaDStream<MessageAndMetadata<T>>,JavaRDD<MessageAndMetadata<T>>> is not applicable for the arguments (PartitionOffsetPair<Object>)

**Comment by dibbhatt** [comment]
Have you changed the pom file ? Anyway, I am making release of 1.0.15 version to spark-packages, then you can get it from repo itself. I have initiated the release and once done ,will let you know

**Comment by dibbhatt** [comment]
Hi Fred, 

I have released the consumer version 1.0.15 to spark-packages.org

https://spark-packages.org/package/dibbhatt/kafka-spark-consumer

Please update your pom to consume this release and let me know how your test goes. 

Dibyendu

**Comment by yufuxin** [comment]
Hi Dibyendu,
OK, let me update and deploy it to my pre_pro environment,  will tell you the testing result tomorrow.
Thanks,
Fred

**Comment by yufuxin** [comment]
Hi Dibyendu,
The recover logic is working now:

18/09/21 06:32:40 WARN PartitionManager: Got fetch request with offset out of range: 361305671 for Topic tr69data24  partition 27
18/09/21 06:32:40 WARN PartitionManager: Offset reset to LatestTime 361305671 for Topic tr69data24  partition 27
consumer.kafka.OutOfRangeException: Offsets out of range with no configured reset policy for partitions: {tr69data24-27=361305671}
        at consumer.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:75)
        at consumer.kafka.PartitionManager.fetchMessages(PartitionManager.java:278)
        at consumer.kafka.PartitionManager.fill(PartitionManager.java:195)
        at consumer.kafka.PartitionManager.next(PartitionManager.java:134)
        at consumer.kafka.KafkaSparkConsumer.createStream(KafkaSparkConsumer.java:96)
        at consumer.kafka.KafkaSparkConsumer.run(KafkaSparkConsumer.java:118)
        at java.lang.Thread.run(Thread.java:745)
18/09/21 06:32:40 WARN KafkaSparkConsumer: Fetch failed. Refresing Coordinator..
consumer.kafka.OutOfRangeException: Offsets out of range with no configured reset policy for partitions: {tr69data24-27=361305671}
        at consumer.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:75)
        at consumer.kafka.PartitionManager.fetchMessages(PartitionManager.java:278)
        at consumer.kafka.PartitionManager.fill(PartitionManager.java:195)
        at consumer.kafka.PartitionManager.next(PartitionManager.java:134)
        at consumer.kafka.KafkaSparkConsumer.createStream(KafkaSparkConsumer.java:96)
        at consumer.kafka.KafkaSparkConsumer.run(KafkaSparkConsumer.java:118)
        at java.lang.Thread.run(Thread.java:745)
18/09/21 06:32:40 INFO MemoryStore: Block input-3-1537501551067 stored as values in memory (estimated size 1880.0 B, free 362.5 MB)
18/09/21 06:32:40 INFO ZkCoordinator: Refreshing partition manager connections
18/09/21 06:32:40 INFO ZkCoordinator: Deleted partition managers: []
18/09/21 06:32:40 INFO ZkCoordinator: New partition managers: []
18/09/21 06:32:40 INFO ZkCoordinator: Finished refreshing
18/09/21 06:32:41 WARN PartitionManager: Got fetch request with offset out of range: 496294858 for Topic tr69data24  partition 3
18/09/21 06:32:41 WARN PartitionManager: Offset reset to EarliestTime 496294868 for Topic tr69data24  partition 3
18/09/21 06:32:41 WARN PartitionManager: Got fetch request with offset out of range: 301687832 for Topic tr69data24  partition 39
18/09/21 06:32:41 WARN PartitionManager: Offset reset to EarliestTime 301687842 for Topic tr69data24  partition 39
18/09/21 06:32:41 INFO MemoryStore: Block input-3-1537501551068 stored as values in memory (estimated size 1904.0 B, free 362.5 MB)
18/09/21 06:32:41 WARN PartitionManager: Got fetch request with offset out of range: 361305671 for Topic tr69data24  partition 27
18/09/21 06:32:41 WARN PartitionManager: Offset reset to EarliestTime 361305681 for Topic tr69data24  partition 27

and then the failed partitions continue work.

Thanks,
Fred Yu

**Comment by dibbhatt** [comment]
This is great news. Thanks for letting me know. You can monitor the system and close this ticket. Otherwise you can close it now, and if same issue occur, you can re-open

**Comment by yufuxin** [comment]
ok, thanks a lot for your help, I'll close it after several hours  monitoring.

**Comment by dibbhatt** [comment]
hi @yufuxin , if you do not mind, can you tell me name of your organization also if this consumer if running in production in your organization. I need it just for my reference.
