### ISSUE TITLE
Unable to pull Batch info metrics using StreamingListener Interface

### ISSUE THREAD

**Issue by akhld** [dibbhatt/kafka-spark-consumer#6]
I have a jobListener extending StreamingListener interface to perform some tasks onBatchCompleted, it works pretty well with native SparkStreaming and KafkaUtil. But its giving wrong values when i used with this lowlevel consumer.

Here's the Listener class:

	private class JobListenern(ssc: StreamingContext) extends StreamingListener {

	  override def onBatchCompleted(batchCompleted: StreamingListenerBatchCompleted) = synchronized {

	    var totalProcessedRecords = 0L
	    println("====> Total delay:  " + batchCompleted.batchInfo.totalDelay.getOrElse(-1) + " ms")

	    batchCompleted.batchInfo.receivedBlockInfo.foreach { case (_, infos) =>
	      totalProcessedRecords += infos.map(_.numRecords).sum        
	    }
	    println("\n=====> Recieved Events: "+ totalProcessedRecords)

	  }
	}

You can attach it to your ssc as:

    val listen = new JobListenern(ssc)
    ssc.addStreamingListener(listen)

    ssc.start()
    ssc.awaitTermination()

Let me know if there's some other way to pull batch info

**Comment by akhld** [comment]
![kafka-con](https://cloud.githubusercontent.com/assets/5821837/6330944/4abd3600-bba2-11e4-9f8a-bdf7d549dd6e.png)

Any idea on how to get these numbers up?

**Comment by dibbhatt** [comment]
Hi, 
Sorry for replying late on this. 
I think this is an issue with Spark. If you see how I generate the Blocks and writes to BlockManager, I used following call..

_receiver.store(_dataBuffer.iterator());

You can see this in PartitionManager.java line # 216

I think if you write the Block this way, Spark not able to calculate the number of records properly.

You can probably raise a JIRA for Spark.

Dibyendu

**Comment by akhld** [comment]
Thanks for the reply Dibyendu. Will try to raise a JIRA with Spark.

**Comment by dibbhatt** [comment]
Hi @akhld . I have fixed the UI Reporting issue in latest consumer. Please take a look at it and let me know how it looks ..

Dibyendu

**Comment by akhld** [comment]
Ohh nice. Will let you know. :)

**Comment by akhld** [comment]
I cloned the latest version and ran it once, but it doesn't show any metrices in the streaming tab. Previously it was -ve values now its 0.

![image](https://cloud.githubusercontent.com/assets/5821837/8003890/e0007434-0b98-11e5-9e9c-9b3957f728d5.png)

**Comment by dibbhatt** [comment]
Are you pushing messages to Kafka ? Initial few batches comes as Zero. Refresh the page and check if you see the stats

**Comment by akhld** [comment]
Yes, messages are pushed and its consuming and printing the count also.
![image](https://cloud.githubusercontent.com/assets/5821837/8004699/8ab1e3bc-0b9f-11e5-8185-459f918b44a2.png)

I ran the job for a minute, it processed around 50 batches (batch interval being 1 second). And you can see from the image the "Processed Batches" is also broken as its always 1. I'm using spark 1.3.1 and recompiled lowlevel kafka with 1.3.1 version of spark.

**Comment by dibbhatt** [comment]
You have 1.2 setup ? My team has successfully tested in 1.2. Also I am presently doing some work on Spark master ( 1.4) and that works there also . Not tested with 1.3.1 though.

**Comment by akhld** [comment]
I have it just tested on 1.2.2, still the same. I'm trying in local mode.
![image](https://cloud.githubusercontent.com/assets/5821837/8005476/20fe8e9e-0ba8-11e5-8b8c-c35e9e2fd2c8.png)

**Comment by dibbhatt** [comment]
Closing this as latest changes solved this problem

**Comment by dibbhatt** [comment]
Hi @akhld 


I have created a JIRA to track the progress of contributing back this project to Apache Spark.

https://issues.apache.org/jira/browse/SPARK-11045

This project is now presently in spark-packages and I believe this is the correct time to contribute it to Apache Spark Project and give better options to larger community around Kafka Connectivity for Spark Streaming.

kindly Vote for this JIRA.

**Comment by akhld** [comment]
Great, voted already. Hope people will start contributing to it.

On Sat, Oct 10, 2015 at 11:59 AM, Dibyendu Bhattacharya <
notifications@github.com> wrote:

> Hi @akhld <https://github.com/akhld>
>
> I have created a JIRA to track the progress of contributing back this
> project to Apache Spark.
>
> https://issues.apache.org/jira/browse/SPARK-11045
>
> This project is now presently in spark-packages and I believe this is the
> correct time to contribute it to Apache Spark Project and give better
> options to larger community around Kafka Connectivity for Spark Streaming.
>
> kindly Vote for this JIRA.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dibbhatt/kafka-spark-consumer/issues/6#issuecomment-147045584>
> .
>



-- 
Cheers!

**Comment by dibbhatt** [comment]
Thanks a lot Akhil. Much appreciated.
